// apps/vite-sveltekit-example/src/lib/Hx.svelte
<script lang="ts">
	import { svelte } from '@sveltejs/vite-plugin-svelte';
	import { getContext } from 'svelte';

	import type { HTMLAttributes } from 'svelte/elements';

	const { increment, ...headingProps } = $props<
		{
			increment?: number;
		} & HTMLAttributes<HTMLHeadingElement>
	>();

	const contextLevel = getContext<number>('uberschriftLevel') || 1;
	const currentLevel = contextLevel + (increment ?? 0);
	const isDiv = currentLevel >= 7;
</script>

<svelte:element
	this={isDiv ? `div` : `h${currentLevel}`}
	aria-level={isDiv ? currentLevel : undefined}
	{...headingProps}
>
	<slot />
</svelte:element>

// packages/vue/src/Hx.vue
<script setup lang="ts">
import { inject } from "vue";
import { uberschriftLevel } from "./uberschriftSymbol.ts";

const props = withDefaults(
	defineProps<{
		increment?: number;
	}>(),
	{
		increment: 0,
	},
);

const currentLevel = inject(uberschriftLevel, 1);
const level = currentLevel + props.increment;
</script>

<template>
	<component v-if="level < 7" :is="`h${level}`">
		<slot />
	</component>

	<div v-else role="heading" :aria-level="level">
		<slot />
	</div>
</template>
